name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Start xcodebuild test
      run: xcodebuild clean test -scheme DhammaTalks -project DhammaTalks.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 11,OS=15.0'